export interface AdministrativeHierarchy {
  [division: string]: {
    [district: string]: {
      [upazila: string]: string[];
    };
  };
}

export const BD_ADMIN_DATA: AdministrativeHierarchy = {
  Sylhet: {
    Sylhet: {
      'Sylhet Sadar': [
        'Ward 01 (City Corp)',
        'Ward 02 (City Corp)',
        'Ward 03 (City Corp)',
        'Ward 04 (City Corp)',
        'Ward 05 (City Corp)',
        'Ward 14 (Zindabazar)',
        'Ward 15 (Amberkhana)',
        'Ward 21 (Shibganj)',
        'Khadimnagar Union',
        'Hatkhola Union',
        'Jalalabad Union',
        'Mogla Bazar Union',
        'Kandigaon Union',
        'Tukerbazar Union',
      ],
      Beanibazar: [
        'Ward 01 (Pourashava)',
        'Ward 02 (Pourashava)',
        'Alinagar Union',
        'Charkhai Union',
        'Dubag Union',
        'Kurar Bazar Union',
        'Mollapur Union',
        'Mathiura Union',
        'Muria Union',
        'Sheola Union',
        'Tilpara Union',
      ],
      Golapganj: [
        'Golapganj Pourashava',
        'Amura Union',
        'Badepasha Union',
        'Bagha Union',
        'Bhadeshwar Union',
        'Dhaka Dakhin Union',
        'Golapganj Sadar Union',
        'Laxmipasha Union',
        'Sharifganj Union',
        'Budhbaribazar Union',
      ],
      Biswanath: [
        'Biswanath Pourashava',
        'Bishwanath Union',
        'Daulatpur Union',
        'Deokalas Union',
        'Khagail Union',
        'Lamakazi Union',
        'Rampasha Union',
        'Alankari Union',
      ],
      Fenchuganj: [
        'Fenchuganj Sadar Union',
        'Ghilachhara Union',
        'Maijgaon Union',
        'Uttar Kushiara Union',
        'Uttar Fenchuganj Union',
      ],
      Companiganj: [
        'Telikhali Union',
        'Islampur Paschim Union',
        'Islampur Purba Union',
        'Ranikhai Uttar Union',
        'Ranikhai Dakshin Union',
        'Ichhakalirpar Union',
      ],
      Gowainghat: [
        'Jaflong Union',
        'Fatehpur Union',
        'Lengura Union',
        'Nandirgaon Union',
        'Rustampur Union',
        'Towakul Union',
        'Paschim Jaflong Union',
      ],
      Jaintiapur: [
        'Charikatha Union',
        'Fatehpur Union',
        'Jaintiapur Sadar Union',
        'Chiknagul Union',
        'Darbast Union',
        'Nijpat Union',
      ],
      Kanaighat: [
        'Bara Chatul Union',
        'Dakshin Banagram Union',
        'Jhingabari Union',
        'Kanaighat Sadar Union',
        'Purba Dighirpar Union',
        'Rajaganj Union',
        'Satbak Union',
      ],
      Zakiganj: [
        'Zakiganj Pourashava',
        'Barathakuri Union',
        'Barahal Union',
        'Khasrur Union',
        'Manikpur Union',
        'Sultanpur Union',
        'Zakiganj Sadar Union',
      ],
      'South Surma': [
        'Baraikandi Union',
        'Daudpur Union',
        'Jalalpur Union',
        'Kuchai Union',
        'Mogla Bazar Union',
        'Mollargaon Union',
        'Silam Union',
        'Tetli Union',
      ],
      'Osmani Nagar': [
        'Burungabazar Union',
        'Dayamir Union',
        'Goalabazar Union',
        'Sadipur Union',
        'Tajpur Union',
        'Umarergaon Union',
        'Tekerghat Union',
      ],
    },
    Moulvibazar: {
      'Moulvibazar Sadar': [
        'Moulvibazar Pourashava',
        'Akhailkura Union',
        'Amtail Union',
        'Chandnighat Union',
        'Ekatuna Union',
        'Giasnagar Union',
        'Kamalpur Union',
        'Monumukh Union',
        'Mustafapur Union',
        'Nazirabad Union',
      ],
      Sreemangal: [
        'Sreemangal Pourashava',
        'Ashidron Union',
        'Bhunabir Union',
        'Kalapur Union',
        'Mirzapur Union',
        'Rajghat Union',
        'Satgaon Union',
        'Sindurkhan Union',
        'Sreemangal Sadar Union',
      ],
      Kamalganj: [
        'Kamalganj Pourashava',
        'Adampur Union',
        'Alinagar Union',
        'Islampur Union',
        'Kamalganj Sadar Union',
        'Madhabpur Union',
        'Munshibazar Union',
        'Rahimpur Union',
        'Shamshernagar Union',
      ],
      Kulaura: [
        'Kulaura Pourashava',
        'Baramchal Union',
        'Bhadurida Union',
        'Brahmanbazar Union',
        'Hazipur Union',
        'Joychandi Union',
        'Kadirpur Union',
        'Kulaura Sadar Union',
        'Sharifpur Union',
      ],
      Rajnagar: [
        'Fatehpur Union',
        'Mansurnagar Union',
        'Munshibazar Union',
        'Panchgaon Union',
        'Rajnagar Sadar Union',
        'Tengra Union',
        'Uttarbhag Union',
      ],
      Barlekha: [
        'Barlekha Pourashava',
        'Barlekha Sadar Union',
        'Barni Union',
        'Dakshin Shahbazpur Union',
        'Dakhinbhag Union',
        'Nizbahadurpur Union',
        'Sujanagar Union',
        'Talimpur Union',
        'Uttar Shahbazpur Union',
      ],
      Juri: [
        'Fultala Union',
        'Jafornagar Union',
        'Paschim Juri Union',
        'Purba Juri Union',
        'Sagarnal Union',
      ],
    },
    Sunamganj: {
      'Sunamganj Sadar': [
        'Sunamganj Pourashava',
        'Gourarang Union',
        'Jahangirnagar Union',
        'Lakshmanshree Union',
        'Mohanpur Union',
        'Mollapara Union',
        'Rangar Char Union',
        'Surma Union',
      ],
      Chhatak: [
        'Chhatak Pourashava',
        'Bhatgaon Union',
        'Chhatak Sadar Union',
        'Chhaila Afzalabad Union',
        'Dularbazar Union',
        'Gobindaganj Union',
        'Islampur Union',
        'Jhawoa Union',
        'Kalaruka Union',
        'Noarai Union',
      ],
      Jagannathpur: [
        'Jagannathpur Pourashava',
        'Asharkhandi Union',
        'Chilar Char Union',
        'Haldipur Union',
        'Kolkolia Union',
        'Mirpur Union',
        'Pailgaon Union',
        'Patli Union',
        'Ranaping Union',
        'Syedpur Shaharpara Union',
      ],
      Derai: [
        'Derai Pourashava',
        'Bhatipara Union',
        'Charnarchar Union',
        'Derai Sadar Union',
        'Jagdal Union',
        'Karimpur Union',
        'Kulanjoy Union',
        'Rajanagar Union',
        'Sarmangal Union',
      ],
      Tahirpur: [
        'Balijuri Union',
        'Badaghat Union',
        'Dakshin Sreepur Union',
        'Dakshin Baradal Union',
        'Tahirpur Sadar Union',
        'Uttar Baradal Union',
        'Uttar Sreepur Union',
      ],
      Dharmapasha: [
        'Chamardani Union',
        'Bangshikunda Union',
        'Dharmapasha Sadar Union',
        'Joysree Union',
        'Paikarati Union',
        'Sukhair Rajapur Union',
      ],
      Dowarabazar: [
        'Banglabazar Union',
        'Boglabazar Union',
        'Dohalia Union',
        'Dowarabazar Sadar Union',
        'Laxmipur Union',
        'Mannargaon Union',
        'Narsingpur Union',
        'Pandargaon Union',
      ],
    },
    Habiganj: {
      'Habiganj Sadar': [
        'Habiganj Pourashava',
        'Gopaya Union',
        'Laskarpur Union',
        'Lokra Union',
        'Nizampur Union',
        'Nurpur Union',
        'Paikpara Union',
        'Rajiura Union',
        'Richi Union',
        'Sahaji Union',
        'Tegharia Union',
      ],
      Madhabpur: [
        'Madhabpur Pourashava',
        'Adaoir Union',
        'Andiura Union',
        'Baghasura Union',
        'Bahara Union',
        'Bulla Union',
        'Chhatiain Union',
        'Choumohani Union',
        'Dharmaghar Union',
        'Jagadishpur Union',
        'Madhabpur Sadar Union',
      ],
      Nabiganj: [
        'Nabiganj Pourashava',
        'Aushkandi Union',
        'Bausha Union',
        'Debpara Union',
        'Dighalbak Union',
        'Gaznaipur Union',
        'Inathganj Union',
        'Kaliarbhanga Union',
        'Kurshi Union',
        'Nabiganj Sadar Union',
        'Purba Barabak Union',
      ],
      Bahubal: [
        'Bahubal Sadar Union',
        'Bharaura Union',
        'Mirpur Union',
        'Putijuri Union',
        'Satkapon Union',
        'Snanghat Union',
      ],
      Chunarughat: [
        'Chunarughat Pourashava',
        'Ahmadabad Union',
        'Chunarughat Sadar Union',
        'Deorgach Union',
        'Gazipur Union',
        'Mirashi Union',
        'Paikpara Union',
        'Ranigaon Union',
        'Shankhala Union',
        'Ubahata Union',
      ],
      Baniachong: [
        'Baniachong 1 No North-East Union',
        'Baniachong 2 No North-West Union',
        'Baniachong 3 No South-East Union',
        'Baniachong 4 No South-West Union',
        'Daulatpur Union',
        'Kagapasha Union',
        'Khagaura Union',
        'Makrampur Union',
        'Mandari Union',
        'Muradpur Union',
        'Payergaon Union',
        'Pukra Union',
        'Subidpur Union',
      ],
      Lakhai: [
        'Bamoi Union',
        'Bulla Union',
        'Karikachha Union',
        'Lakhai Sadar Union',
        'Murakari Union',
        'Muriauk Union',
      ],
      Ajmiriganj: [
        'Ajmiriganj Pourashava',
        'Ajmiriganj Sadar Union',
        'Badolpur Union',
        'Jolsuka Union',
        'Kakailseo Union',
        'Shibpasha Union',
      ],
    },
  },
};

export type DepartmentCategory =
  | 'All'
  | 'Civil Administration'
  | 'Law Enforcement & Police'
  | 'Land & Revenue'
  | 'Elected Representatives'
  | 'Public Health & Medical'
  | 'Emergency & Utilities';

export interface PersonRecord {
  id: string;
  name: string;
  nameBangla: string;
  designation: string;
  designationBangla: string;
  department: DepartmentCategory;
  roleType: 'representative' | 'official';
  division: string;
  district: string;
  upazila?: string;
  union?: string;
  office: string;
  officeBangla: string;
  phone: string;
  altPhone?: string;
  email: string;
  address: string;
  officeHours: string;
  servicesProvided: string[];
  verified: boolean;
  avatar: string;
  termOrBatch?: string;
  emergencyHotline?: string;
  jurisdictionNotes?: string;
}

export const SYLHET_DIRECTORY_DATA: PersonRecord[] = [
  // ==================== SYLHET DISTRICT ====================
  // 1. Divisional Commissioner
  {
    id: 'syl-div-1',
    name: 'Abu Ahmed Siddique, ndc',
    nameBangla: 'আবু আহমেদ সিদ্দিকী, এনডিসি',
    designation: 'Divisional Commissioner, Sylhet',
    designationBangla: 'বিভাগীয় কমিশনার, সিলেট',
    department: 'Civil Administration',
    roleType: 'official',
    division: 'Sylhet',
    district: 'Sylhet',
    upazila: 'Sylhet Sadar',
    union: 'Ward 15 (Amberkhana)',
    office: 'Office of the Divisional Commissioner, Sylhet',
    officeBangla: 'বিভাগীয় কমিশনারের কার্যালয়, সিলেট',
    phone: '+880 2996634001',
    altPhone: '+880 1713-300100',
    email: 'divcomsylhet@mopa.gov.bd',
    address: 'Divisional Headquarters Complex, Amberkhana, Sylhet-3100',
    officeHours: 'Sunday - Thursday: 9:00 AM - 5:00 PM',
    servicesProvided: [
      'Divisional Administrative Coordination',
      'Revenue Appeal Hearings & Land Dispute Tribunal',
      'Disaster Management & Relief Monitoring',
      'Citizen Grievance Redressal (GRS)',
    ],
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    termOrBatch: '13th BCS (Administration)',
    emergencyHotline: '333',
    jurisdictionNotes: 'All 4 Districts of Sylhet Division (Sylhet, Moulvibazar, Sunamganj, Habiganj)',
  },

  // 2. Deputy Commissioner Sylhet
  {
    id: 'syl-dc-1',
    name: 'Mohammad Sher Mahbub Murad',
    nameBangla: 'মোহাম্মদ শের মাহবুব মুরাদ',
    designation: 'Deputy Commissioner & District Magistrate (DC)',
    designationBangla: 'জেলা প্রশাসক ও জেলা ম্যাজিস্ট্রেট (ডিসি)',
    department: 'Civil Administration',
    roleType: 'official',
    division: 'Sylhet',
    district: 'Sylhet',
    upazila: 'Sylhet Sadar',
    union: 'Ward 14 (Zindabazar)',
    office: "Deputy Commissioner's Office, Sylhet Collectorate",
    officeBangla: 'জেলা প্রশাসকের কার্যালয়, সিলেট কালেক্টরেট',
    phone: '+880 2996634500',
    altPhone: '+880 1713-000501',
    email: 'dcsylhet@mopa.gov.bd',
    address: 'Collectorate Building, Court Point, Bandar Bazar, Sylhet-3100',
    officeHours: 'Sunday - Thursday: 9:00 AM - 5:00 PM (Public Hearing: Wednesday 10:00 AM)',
    servicesProvided: [
      'District Administration & Law & Order Control',
      'Citizenship & Character Verification',
      'Firearms License & Explosive Permits',
      'Revenue Court & Land Acquisition Processing',
    ],
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
    termOrBatch: '24th BCS (Administration)',
    emergencyHotline: '02996634505',
    jurisdictionNotes: 'Entire Sylhet District (13 Upazilas & Sylhet City Corporation)',
  },

  // 3. Superintendent of Police (SP) Sylhet
  {
    id: 'syl-sp-1',
    name: 'Mohammad Mahbubur Rahman, PPM',
    nameBangla: 'মোহাম্মদ মাহবুবুর রহমান, পিপিএম',
    designation: 'Superintendent of Police (SP), Sylhet District',
    designationBangla: 'পুলিশ সুপার (এসপি), সিলেট জেলা',
    department: 'Law Enforcement & Police',
    roleType: 'official',
    division: 'Sylhet',
    district: 'Sylhet',
    upazila: 'Sylhet Sadar',
    union: 'Ward 14 (Zindabazar)',
    office: 'District Police Headquarters, Sylhet',
    officeBangla: 'জেলা পুলিশ সুপারের কার্যালয়, সিলেট',
    phone: '+880 2996637000',
    altPhone: '+880 1713-374350',
    email: 'spsylhet@police.gov.bd',
    address: 'Nayasarak Road, Kumarpara, Sylhet-3100',
    officeHours: '24/7 Police Operations (Office: Sun-Thu 9 AM - 5 PM)',
    servicesProvided: [
      'District Crime Control & Law Enforcement',
      'Police Clearance Certificate Verification',
      'Emergency 999 Police Response Deployment',
      'VIP & Public Gathering Security Clearance',
    ],
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&auto=format&fit=crop&q=80',
    termOrBatch: '25th BCS (Police)',
    emergencyHotline: '999',
    jurisdictionNotes: 'Sylhet District Rural & Upazila Thanas',
  },

  // 4. Police Commissioner, SMP
  {
    id: 'syl-smp-1',
    name: 'Md. Rezaul Karim, BPM',
    nameBangla: 'মো. রেজাউল করিম, বিপিএম',
    designation: 'Police Commissioner, Sylhet Metropolitan Police (SMP)',
    designationBangla: 'পুলিশ কমিশনার, সিলেট মেট্রোপলিটন পুলিশ (এসএমপি)',
    department: 'Law Enforcement & Police',
    roleType: 'official',
    division: 'Sylhet',
    district: 'Sylhet',
    upazila: 'Sylhet Sadar',
    union: 'Ward 15 (Amberkhana)',
    office: 'SMP Headquarters, Nayasarak, Sylhet',
    officeBangla: 'এসএমপি সদর দপ্তর, নয়াসড়ক, সিলেট',
    phone: '+880 2996634567',
    altPhone: '+880 1713-374300',
    email: 'commissioner@smp.gov.bd',
    address: 'SMP Head Office, Nayasarak, Sylhet-3100',
    officeHours: '24/7 Operations Room',
    servicesProvided: [
      'Metropolitan Traffic Control & CCTVs',
      'City Thana Supervision (Kotwali, Shah Paran, Airport, Mogla Bazar)',
      'Victim Support Center & Cyber Crime Cell',
      'Online GD & Emergency Response',
    ],
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&auto=format&fit=crop&q=80',
    termOrBatch: '20th BCS (Police)',
    emergencyHotline: '01713-374300',
    jurisdictionNotes: 'Sylhet Metropolitan Area (All 42 City Corporation Wards)',
  },

  // 5. Mayor, Sylhet City Corporation
  {
    id: 'syl-mayor-1',
    name: 'Md. Anwaruzzaman Chowdhury',
    nameBangla: 'মো. আনোয়ারুজ্জামান চৌধুরী',
    designation: 'City Mayor, Sylhet City Corporation (SCC)',
    designationBangla: 'মেয়র, সিলেট সিটি কর্পোরেশন',
    department: 'Elected Representatives',
    roleType: 'representative',
    division: 'Sylhet',
    district: 'Sylhet',
    upazila: 'Sylhet Sadar',
    union: 'Ward 14 (Zindabazar)',
    office: 'Sylhet City Corporation Bhaban, Topkhana',
    officeBangla: 'সিলেট সিটি কর্পোরেশন ভবন, তোপখানা',
    phone: '+880 2996633333',
    altPhone: '+880 1711-889900',
    email: 'mayor@scc.gov.bd',
    address: 'City Corporation Complex, Topkhana, Sylhet-3100',
    officeHours: 'Sunday - Thursday: 9:00 AM - 5:00 PM',
    servicesProvided: [
      'City Urban Infrastructure & Drainage Maintenance',
      'Birth & Death Registration Certification',
      'Trade License Issuance & Renewal',
      'Holding Tax Assessment & Waste Management',
    ],
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=300&auto=format&fit=crop&q=80',
    termOrBatch: 'Elected Term: 2023 - Present',
    emergencyHotline: '01713-374400 (SCC Control)',
    jurisdictionNotes: 'Sylhet City Corporation (Wards 1 to 42)',
  },

  // 6. Member of Parliament (Sylhet-1: Sadar & City)
  {
    id: 'syl-mp-1',
    name: 'Dr. A. K. Abdul Momen',
    nameBangla: 'ড. এ. কে. আব্দুল মোমেন',
    designation: 'Member of Parliament (Sylhet-1 Constituency)',
    designationBangla: 'সংসদ সদস্য (সিলেট-১ আসন)',
    department: 'Elected Representatives',
    roleType: 'representative',
    division: 'Sylhet',
    district: 'Sylhet',
    upazila: 'Sylhet Sadar',
    union: 'Ward 01 (City Corp)',
    office: 'Parliamentary Constituency Office, Dhopadighirpar, Sylhet',
    officeBangla: 'সংসদ সদস্য কার্যালয়, ধোপাদীঘিরপাড়, সিলেট',
    phone: '+880 1711-524300',
    altPhone: '+880 2996638899',
    email: 'mp.sylhet1@parliament.gov.bd',
    address: 'House 12, Dhopadighir Purbo Par, Sylhet',
    officeHours: 'Public Audience: Friday - Saturday 10:00 AM - 2:00 PM',
    servicesProvided: [
      'Constituency Development Project Approval',
      'National Policy & Legislative Representation',
      'MP Recommendation Letters for Citizens',
      'TR / Kabikha Rural Infrastructure Grants',
    ],
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    termOrBatch: '12th National Parliament',
    emergencyHotline: '01711-524300',
    jurisdictionNotes: 'Sylhet Sadar Upazila & Sylhet City Corporation Area',
  },

  // 7. UNO Sylhet Sadar
  {
    id: 'syl-uno-sadar',
    name: 'Kazi Mohiuddin Jinat',
    nameBangla: 'কাজী মহিউদ্দিন জিনাত',
    designation: 'Upazila Nirbahi Officer (UNO), Sylhet Sadar',
    designationBangla: 'উপজেলা নির্বাহী অফিসার (ইউএনও), সিলেট সদর',
    department: 'Civil Administration',
    roleType: 'official',
    division: 'Sylhet',
    district: 'Sylhet',
    upazila: 'Sylhet Sadar',
    union: 'Khadimnagar Union',
    office: 'Upazila Parishad Complex, Khadimnagar, Sylhet',
    officeBangla: 'উপজেলা পরিষদ কমপ্লেক্স, খাদিমপাড়া, সিলেট',
    phone: '+880 2996641200',
    altPhone: '+880 1730-331070',
    email: 'unosylhetsadar@mopa.gov.bd',
    address: 'Khadimnagar, Tamabil Highway, Sylhet-3103',
    officeHours: 'Sunday - Thursday: 9:00 AM - 5:00 PM',
    servicesProvided: [
      'Upazila Development Coordination & Tendering',
      'Mobile Court Execution & Public Safety Enforcement',
      'Relief Distribution & Social Safety Net Monitoring',
      'Primary & Secondary Education Supervision',
    ],
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80',
    termOrBatch: '34th BCS (Administration)',
    emergencyHotline: '01730-331070',
    jurisdictionNotes: 'Sylhet Sadar Upazila (All 8 Unions)',
  },

  // 8. AC Land Sylhet Sadar
  {
    id: 'syl-acland-sadar',
    name: 'Saima Sharmin',
    nameBangla: 'সায়মা শারমিন',
    designation: 'Assistant Commissioner (Land) - AC Land',
    designationBangla: 'সহকারী কমিশনার (ভূমি) - এসি ল্যান্ড',
    department: 'Land & Revenue',
    roleType: 'official',
    division: 'Sylhet',
    district: 'Sylhet',
    upazila: 'Sylhet Sadar',
    union: 'Khadimnagar Union',
    office: 'Upazila Land Office, Khadimnagar, Sylhet',
    officeBangla: 'উপজেলা ভূমি অফিস, খাদিমপাড়া, সিলেট',
    phone: '+880 2996641250',
    altPhone: '+880 1710-442211',
    email: 'aclandsylhetsadar@mopa.gov.bd',
    address: 'Land Office Complex, Khadimnagar, Sylhet-3103',
    officeHours: 'Sunday - Thursday: 9:00 AM - 5:00 PM',
    servicesProvided: [
      'e-Mutation (ই-নামজারি) Application Hearing',
      'Land Development Tax (LDT) Dispute Redressal',
      'Khas Land Lease & Vested Property Management',
      'Khatian (Porcha) Verification & Correction',
    ],
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=300&auto=format&fit=crop&q=80',
    termOrBatch: '38th BCS (Administration)',
    emergencyHotline: '16122 (Land Helpline)',
    jurisdictionNotes: 'All Mauzas of Sylhet Sadar Upazila',
  },

  // 9. Officer-in-Charge (OC) Kotwali Model Thana, Sylhet
  {
    id: 'syl-oc-kotwali',
    name: 'Md. Nazrul Islam',
    nameBangla: 'মো. নজরুল ইসলাম',
    designation: 'Officer-in-Charge (OC), Kotwali Model Police Station',
    designationBangla: 'অফিসার ইনচার্জ (ওসি), কোতোয়ালী মডেল থানা',
    department: 'Law Enforcement & Police',
    roleType: 'official',
    division: 'Sylhet',
    district: 'Sylhet',
    upazila: 'Sylhet Sadar',
    union: 'Ward 14 (Zindabazar)',
    office: 'Kotwali Model Thana, Zindabazar, Sylhet',
    officeBangla: 'কোতোয়ালী মডেল থানা, জিন্দাবাজার, সিলেট',
    phone: '+880 2996634123',
    altPhone: '+880 1713-374301',
    email: 'ockotwalisylhet@police.gov.bd',
    address: 'Zindabazar Main Road, Sylhet-3100',
    officeHours: '24 Hours Duty Officer Available',
    servicesProvided: [
      'First Information Report (FIR) Filing',
      'General Diary (GD) Registration',
      'Thana Emergency Patrol & Crime Investigation',
      'Citizen Protection & Lost Article Inquiries',
    ],
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80',
    termOrBatch: 'Bangladesh Police Service',
    emergencyHotline: '999 / 01713-374301',
    jurisdictionNotes: 'Zindabazar, Bandarbazar, Ambarkhana, Court Point & Central Sylhet',
  },

  // 10. Civil Surgeon Sylhet (Health)
  {
    id: 'syl-cs-1',
    name: 'Dr. S. M. Shahriar',
    nameBangla: 'ডা. এস. এম. শাহরিয়ার',
    designation: 'Civil Surgeon, Sylhet District',
    designationBangla: 'সিভিল সার্জন, সিলেট জেলা',
    department: 'Public Health & Medical',
    roleType: 'official',
    division: 'Sylhet',
    district: 'Sylhet',
    upazila: 'Sylhet Sadar',
    union: 'Ward 03 (City Corp)',
    office: 'Civil Surgeon Office, Chauhatta, Sylhet',
    officeBangla: 'সিভিল সার্জন কার্যালয়, চৌহাট্টা, সিলেট',
    phone: '+880 2996636700',
    altPhone: '+880 1711-345678',
    email: 'cs_sylhet@dghs.gov.bd',
    address: 'Chauhatta Medical Road, Sylhet-3100',
    officeHours: 'Sunday - Thursday: 9:00 AM - 5:00 PM',
    servicesProvided: [
      'District Public Health Surveillance & Immunization (EPI)',
      'Government Hospital & Community Clinic Supervision',
      'Private Clinic & Diagnostic Center Licensing Verification',
      'Medical Board Examinations & Fitness Certificates',
    ],
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&auto=format&fit=crop&q=80',
    termOrBatch: '27th BCS (Health)',
    emergencyHotline: '16263 (Health Helpline)',
    jurisdictionNotes: 'All Government Upazila Health Complexes & Diagnostic Labs across Sylhet',
  },

  // 11. Director, MAG Osmani Medical College Hospital
  {
    id: 'syl-osmani-1',
    name: 'Brigadier General Dr. Mahbubur Rahman',
    nameBangla: 'ব্রিগেডিয়ার জেনারেল ডা. মাহবুবুর রহমান',
    designation: 'Director, Sylhet MAG Osmani Medical College Hospital',
    designationBangla: 'পরিচালক, সিলেট এমএজি ওসমানী মেডিকেল কলেজ হাসপাতাল',
    department: 'Public Health & Medical',
    roleType: 'official',
    division: 'Sylhet',
    district: 'Sylhet',
    upazila: 'Sylhet Sadar',
    union: 'Ward 03 (City Corp)',
    office: 'MAG Osmani Medical College Hospital, Kazitula Road, Sylhet',
    officeBangla: 'এমএজি ওসমানী মেডিকেল কলেজ হাসপাতাল, সিলেট',
    phone: '+880 2996636000',
    altPhone: '+880 1713-334455',
    email: 'director@somch.gov.bd',
    address: 'Medical Road, Kajolshah, Sylhet-3100',
    officeHours: 'Emergency: 24/7 | OPD: 8:00 AM - 2:30 PM',
    servicesProvided: [
      '24/7 Emergency Casualty & Trauma Care',
      'Specialized Inpatient & Outpatient Departments',
      'One-Stop Crisis Center (OCC) for Women',
      'Intensive Care Unit (ICU) & Coronary Care',
    ],
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=300&auto=format&fit=crop&q=80',
    termOrBatch: 'Bangladesh Army Medical Corps',
    emergencyHotline: '02996636000',
    jurisdictionNotes: 'Tertiary Referral Hospital for Entire Sylhet Division',
  },

  // 12. UNO Beanibazar
  {
    id: 'syl-uno-beanibazar',
    name: 'Afroz Sultana',
    nameBangla: 'আফরোজ সুলতানা',
    designation: 'Upazila Nirbahi Officer (UNO), Beanibazar',
    designationBangla: 'উপজেলা নির্বাহী অফিসার (ইউএনও), বিয়ানীবাজার',
    department: 'Civil Administration',
    roleType: 'official',
    division: 'Sylhet',
    district: 'Sylhet',
    upazila: 'Beanibazar',
    union: 'Ward 01 (Pourashava)',
    office: 'Upazila Parishad Complex, Beanibazar, Sylhet',
    officeBangla: 'উপজেলা পরিষদ কমপ্লেক্স, বিয়ানীবাজার, সিলেট',
    phone: '+880 2996645010',
    altPhone: '+880 1730-331072',
    email: 'unobeanibazar@mopa.gov.bd',
    address: 'College Road, Beanibazar Sadar, Sylhet-3170',
    officeHours: 'Sunday - Thursday: 9:00 AM - 5:00 PM',
    servicesProvided: [
      'Expatriate Citizen Property Protection & Liaison',
      'Upazila Parishad Scheme Implementations',
      'Food Grain Storage & VGF Distribution',
      'Local Dispute Mediation & Executive Magistrate Duties',
    ],
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?w=300&auto=format&fit=crop&q=80',
    termOrBatch: '35th BCS (Administration)',
    emergencyHotline: '01730-331072',
    jurisdictionNotes: 'Beanibazar Pourashava and 10 Unions',
  },

  // 13. Upazila Parishad Chairman Beanibazar
  {
    id: 'syl-chairman-beanibazar',
    name: 'Abul Kashem Chowdhury',
    nameBangla: 'আবুল কাশেম চৌধুরী',
    designation: 'Upazila Parishad Chairman, Beanibazar',
    designationBangla: 'উপজেলা পরিষদ চেয়ারম্যান, বিয়ানীবাজার',
    department: 'Elected Representatives',
    roleType: 'representative',
    division: 'Sylhet',
    district: 'Sylhet',
    upazila: 'Beanibazar',
    union: 'Ward 01 (Pourashava)',
    office: 'Upazila Parishad Bhaban, Beanibazar',
    officeBangla: 'উপজেলা পরিষদ ভবন, বিয়ানীবাজার',
    phone: '+880 1711-229988',
    email: 'chairman.beanibazar@localgov.gov.bd',
    address: 'Parishad Road, Beanibazar Sadar, Sylhet',
    officeHours: 'Sunday - Thursday: 10:00 AM - 4:00 PM',
    servicesProvided: [
      'Rural Roads & Culvert Construction Approval',
      'Upazila Development Fund Allocation',
      'Public Grievance Hearings & Recommendations',
    ],
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=300&auto=format&fit=crop&q=80',
    termOrBatch: 'Elected Term: 2024 - 2029',
    emergencyHotline: '01711-229988',
    jurisdictionNotes: 'Beanibazar Upazila Local Governance',
  },

  // 14. UNO Golapganj
  {
    id: 'syl-uno-golapganj',
    name: 'Md. Ali Hossain',
    nameBangla: 'মো. আলী হোসেন',
    designation: 'Upazila Nirbahi Officer (UNO), Golapganj',
    designationBangla: 'উপজেলা নির্বাহী অফিসার (ইউএনও), গোলাপগঞ্জ',
    department: 'Civil Administration',
    roleType: 'official',
    division: 'Sylhet',
    district: 'Sylhet',
    upazila: 'Golapganj',
    union: 'Golapganj Pourashava',
    office: 'Upazila Parishad Complex, Golapganj, Sylhet',
    officeBangla: 'উপজেলা পরিষদ কমপ্লেক্স, গোলাপগঞ্জ, সিলেট',
    phone: '+880 2996647100',
    altPhone: '+880 1730-331073',
    email: 'unogolapganj@mopa.gov.bd',
    address: 'Golapganj Thana Road, Sylhet-3160',
    officeHours: 'Sunday - Thursday: 9:00 AM - 5:00 PM',
    servicesProvided: [
      'Gas Exploration & Industrial Zone Coordination',
      'Expatriate Community Welfare & Land Guard Services',
      'Disaster Relief & Canal Excavation Monitoring',
    ],
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=300&auto=format&fit=crop&q=80',
    termOrBatch: '36th BCS (Administration)',
    emergencyHotline: '01730-331073',
    jurisdictionNotes: 'Golapganj Pourashava and 11 Unions',
  },

  // 15. Union Parishad Chairman (Dhaka Dakhin, Golapganj)
  {
    id: 'syl-up-dhakadakhin',
    name: 'M. A. Rahim',
    nameBangla: 'এম. এ. রহিম',
    designation: 'Union Parishad Chairman, Dhaka Dakhin UP',
    designationBangla: 'ইউনিয়ন পরিষদ চেয়ারম্যান, ঢাকা দক্ষিণ ইউপি',
    department: 'Elected Representatives',
    roleType: 'representative',
    division: 'Sylhet',
    district: 'Sylhet',
    upazila: 'Golapganj',
    union: 'Dhaka Dakhin Union',
    office: 'Dhaka Dakhin Union Parishad Complex, Golapganj',
    officeBangla: 'ঢাকা দক্ষিণ ইউনিয়ন পরিষদ কমপ্লেক্স, গোলাপগঞ্জ',
    phone: '+880 1715-998877',
    email: 'upchairman.dhakadakhin@localgov.gov.bd',
    address: 'Dhaka Dakhin Bazar, Golapganj, Sylhet-3161',
    officeHours: 'Sunday - Thursday: 9:30 AM - 3:30 PM',
    servicesProvided: [
      'Citizen Citizenship / Character Certificate (নাগরিকত্ব সনদ)',
      'Inheritance / Warisan Certificate (ওয়ারিশান সনদ)',
      'Rural Village Court (গ্রাম আদালত) Dispute Resolution',
      'Vulnerable Group Feeding (VGF) Card Issuance',
    ],
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300&auto=format&fit=crop&q=80',
    termOrBatch: 'Elected Term: 2022 - 2027',
    emergencyHotline: '01715-998877',
    jurisdictionNotes: 'Dhaka Dakhin Union Wards 1 to 9',
  },

  // ==================== MOULVIBAZAR DISTRICT ====================
  // 16. Deputy Commissioner Moulvibazar
  {
    id: 'mbz-dc-1',
    name: 'Dr. Urmi Binte Saiful',
    nameBangla: 'ড. উর্মি বিনতে সাইফুল',
    designation: 'Deputy Commissioner & District Magistrate (DC), Moulvibazar',
    designationBangla: 'জেলা প্রশাসক ও জেলা ম্যাজিস্ট্রেট (ডিসি), মৌলভীবাজার',
    department: 'Civil Administration',
    roleType: 'official',
    division: 'Sylhet',
    district: 'Moulvibazar',
    upazila: 'Moulvibazar Sadar',
    union: 'Moulvibazar Pourashava',
    office: "Deputy Commissioner's Office, Moulvibazar Collectorate",
    officeBangla: 'জেলা প্রশাসকের কার্যালয়, মৌলভীবাজার কালেক্টরেট',
    phone: '+880 2996681001',
    altPhone: '+880 1713-000502',
    email: 'dcmoulvibazar@mopa.gov.bd',
    address: 'Collectorate Building, Court Road, Moulvibazar-3200',
    officeHours: 'Sunday - Thursday: 9:00 AM - 5:00 PM',
    servicesProvided: [
      'Tea Estate Worker Welfare & Land Lease Monitoring',
      'Haor Ecology Protection & Wetland Governance',
      'Law & Order and District Executive Magistracy',
      'Expatriate Citizen One-Stop Service Desk',
    ],
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=300&auto=format&fit=crop&q=80',
    termOrBatch: '24th BCS (Administration)',
    emergencyHotline: '02996681005',
    jurisdictionNotes: 'Moulvibazar District (7 Upazilas, 5 Municipalities)',
  },

  // 17. Superintendent of Police (SP) Moulvibazar
  {
    id: 'mbz-sp-1',
    name: 'Md. Monjur Ahmed, PPM',
    nameBangla: 'মো. মনজুর আহমেদ, পিপিএম',
    designation: 'Superintendent of Police (SP), Moulvibazar',
    designationBangla: 'পুলিশ সুপার (এসপি), মৌলভীবাজার',
    department: 'Law Enforcement & Police',
    roleType: 'official',
    division: 'Sylhet',
    district: 'Moulvibazar',
    upazila: 'Moulvibazar Sadar',
    union: 'Moulvibazar Pourashava',
    office: 'District Police Office, Court Road, Moulvibazar',
    officeBangla: 'জেলা পুলিশ কার্যালয়, কোর্ট রোড, মৌলভীবাজার',
    phone: '+880 2996681200',
    altPhone: '+880 1713-374360',
    email: 'spmoulvibazar@police.gov.bd',
    address: 'Police Lines, Sreemangal Road, Moulvibazar-3200',
    officeHours: '24/7 Police Operations',
    servicesProvided: [
      'District Law & Order & Highway Patrol',
      'Tourist Police Security for Sreemangal & Madhabkunda',
      'Passport & Verification Desk',
      'Community Policing & Drug Prevention Cell',
    ],
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
    termOrBatch: '27th BCS (Police)',
    emergencyHotline: '999 / 01713-374360',
    jurisdictionNotes: 'All Thanas of Moulvibazar District',
  },

  // 18. UNO Sreemangal
  {
    id: 'mbz-uno-sreemangal',
    name: 'Md. Abu Taleb',
    nameBangla: 'মো. আবু তালেব',
    designation: 'Upazila Nirbahi Officer (UNO), Sreemangal',
    designationBangla: 'উপজেলা নির্বাহী অফিসার (ইউএনও), শ্রীমঙ্গল',
    department: 'Civil Administration',
    roleType: 'official',
    division: 'Sylhet',
    district: 'Moulvibazar',
    upazila: 'Sreemangal',
    union: 'Sreemangal Pourashava',
    office: 'Upazila Parishad Complex, Sreemangal, Moulvibazar',
    officeBangla: 'উপজেলা পরিষদ কমপ্লেক্স, শ্রীমঙ্গল, মৌলভীবাজার',
    phone: '+880 2996683100',
    altPhone: '+880 1730-331080',
    email: 'unosreemangal@mopa.gov.bd',
    address: 'Bhanugach Road, Sreemangal, Moulvibazar-3210',
    officeHours: 'Sunday - Thursday: 9:00 AM - 5:00 PM',
    servicesProvided: [
      'Tourism Eco-zone Conservation & Monitoring',
      'Tea Garden Community Primary School Upgrades',
      'Executive Magistrate Mobile Courts on Food Adulteration',
      'Tourism Safety & Foreign Visitor Inquiries',
    ],
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&auto=format&fit=crop&q=80',
    termOrBatch: '35th BCS (Administration)',
    emergencyHotline: '01730-331080',
    jurisdictionNotes: 'Sreemangal Upazila (9 Unions, 1 Pourashava, 40+ Tea Gardens)',
  },

  // 19. AC Land Sreemangal
  {
    id: 'mbz-acland-sreemangal',
    name: 'Tanvir Hossain',
    nameBangla: 'তানভীর হোসেন',
    designation: 'Assistant Commissioner (Land) - AC Land, Sreemangal',
    designationBangla: 'সহকারী কমিশনার (ভূমি) - এসি ল্যান্ড, শ্রীমঙ্গল',
    department: 'Land & Revenue',
    roleType: 'official',
    division: 'Sylhet',
    district: 'Moulvibazar',
    upazila: 'Sreemangal',
    union: 'Sreemangal Pourashava',
    office: 'Upazila Land Office, Station Road, Sreemangal',
    officeBangla: 'উপজেলা ভূমি অফিস, স্টেশন রোড, শ্রীমঙ্গল',
    phone: '+880 2996683150',
    altPhone: '+880 1714-889911',
    email: 'aclandsreemangal@mopa.gov.bd',
    address: 'Station Road, Sreemangal, Moulvibazar',
    officeHours: 'Sunday - Thursday: 9:00 AM - 5:00 PM',
    servicesProvided: [
      'Mutation & Record of Rights (Khatian) Verification',
      'Tea Grant Land Demarcation & Boundary Resolution',
      'Online Land Revenue Payment Consultation',
    ],
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&auto=format&fit=crop&q=80',
    termOrBatch: '38th BCS (Administration)',
    emergencyHotline: '16122',
    jurisdictionNotes: 'All Land Mauzas of Sreemangal Upazila',
  },

  // 20. Member of Parliament (Moulvibazar-4: Sreemangal & Kamalganj)
  {
    id: 'mbz-mp-4',
    name: 'Md. Abdus Shahid',
    nameBangla: 'মো. আব্দুস শহীদ',
    designation: 'Member of Parliament (Moulvibazar-4 Constituency)',
    designationBangla: 'সংসদ সদস্য (মৌলভীবাজার-৪ আসন)',
    department: 'Elected Representatives',
    roleType: 'representative',
    division: 'Sylhet',
    district: 'Moulvibazar',
    upazila: 'Sreemangal',
    union: 'Sreemangal Pourashava',
    office: 'Parliamentary Office, Sreemangal Main Road',
    officeBangla: 'সংসদ সদস্যের কার্যালয়, শ্রীমঙ্গল',
    phone: '+880 1711-546789',
    email: 'mp.mbz4@parliament.gov.bd',
    address: 'Sreemangal Town, Moulvibazar',
    officeHours: 'Public Audience on Weekends',
    servicesProvided: [
      'Constituency Road & Bridge Development Projects',
      'Tea Worker Housing & Sanitation Allocations',
      'Agricultural Subsidy Schemes Approval',
    ],
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    termOrBatch: '12th National Parliament',
    emergencyHotline: '01711-546789',
    jurisdictionNotes: 'Sreemangal & Kamalganj Upazilas',
  },

  // ==================== SUNAMGANJ DISTRICT ====================
  // 21. Deputy Commissioner Sunamganj
  {
    id: 'snm-dc-1',
    name: 'Mohammad Rashed Iqbal Chowdhury',
    nameBangla: 'মোহাম্মদ রাশেদ ইকবাল চৌধুরী',
    designation: 'Deputy Commissioner & District Magistrate (DC), Sunamganj',
    designationBangla: 'জেলা প্রশাসক ও জেলা ম্যাজিস্ট্রেট (ডিসি), সুনামগঞ্জ',
    department: 'Civil Administration',
    roleType: 'official',
    division: 'Sylhet',
    district: 'Sunamganj',
    upazila: 'Sunamganj Sadar',
    union: 'Sunamganj Pourashava',
    office: "Deputy Commissioner's Office, Sunamganj Collectorate",
    officeBangla: 'জেলা প্রশাসকের কার্যালয়, সুনামগঞ্জ কালেক্টরেট',
    phone: '+880 2996661001',
    altPhone: '+880 1713-000503',
    email: 'dcsunamganj@mopa.gov.bd',
    address: 'Collectorate Bhaban, Surma River Road, Sunamganj-3000',
    officeHours: 'Sunday - Thursday: 9:00 AM - 5:00 PM',
    servicesProvided: [
      'Haor Boro Crop Protection Embankment (Beri-Bandh) Oversight',
      'Fishery & Jalmahal Lease Policy Implementation',
      'Disaster Early Warning & Relief Operations (Flood & Flashfloods)',
      'Tanguar Haor Ramsar Site Ecological Management',
    ],
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80',
    termOrBatch: '24th BCS (Administration)',
    emergencyHotline: '02996661005 (Flood Cell)',
    jurisdictionNotes: 'Entire Sunamganj District (12 Upazilas & Extensive Haor Basin)',
  },

  // 22. Superintendent of Police (SP) Sunamganj
  {
    id: 'snm-sp-1',
    name: 'A. F. M. Anwar Hossain Khan, PPM',
    nameBangla: 'এ. এফ. এম. আনোয়ার হোসেন খান, পিপিএম',
    designation: 'Superintendent of Police (SP), Sunamganj',
    designationBangla: 'পুলিশ সুপার (এসপি), সুনামগঞ্জ',
    department: 'Law Enforcement & Police',
    roleType: 'official',
    division: 'Sylhet',
    district: 'Sunamganj',
    upazila: 'Sunamganj Sadar',
    union: 'Sunamganj Pourashava',
    office: 'District Police Headquarters, Sunamganj',
    officeBangla: 'জেলা পুলিশ কার্যালয়, সুনামগঞ্জ',
    phone: '+880 2996661200',
    altPhone: '+880 1713-374370',
    email: 'spsunamganj@police.gov.bd',
    address: 'Police Lines, Court Road, Sunamganj-3000',
    officeHours: '24/7 Water Police & Thana Operations',
    servicesProvided: [
      'Riverine Patrol & Haor Waterway Security',
      'Border Surveillance in Tahirpur & Dowarabazar',
      'Sand & Mineral Extraction Transport Safety',
    ],
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&auto=format&fit=crop&q=80',
    termOrBatch: '25th BCS (Police)',
    emergencyHotline: '999 / 01713-374370',
    jurisdictionNotes: 'All 12 Upazila Thanas in Sunamganj',
  },

  // 23. UNO Chhatak
  {
    id: 'snm-uno-chhatak',
    name: 'Golam Mustafa Munna',
    nameBangla: 'গোলাম মোস্তফা মুন্না',
    designation: 'Upazila Nirbahi Officer (UNO), Chhatak',
    designationBangla: 'উপজেলা নির্বাহী অফিসার (ইউএনও), ছাতক',
    department: 'Civil Administration',
    roleType: 'official',
    division: 'Sylhet',
    district: 'Sunamganj',
    upazila: 'Chhatak',
    union: 'Chhatak Pourashava',
    office: 'Upazila Parishad Complex, Chhatak, Sunamganj',
    officeBangla: 'উপজেলা পরিষদ কমপ্লেক্স, ছাতক, সুনামগঞ্জ',
    phone: '+880 2996663100',
    altPhone: '+880 1730-331090',
    email: 'unochhatak@mopa.gov.bd',
    address: 'Chhatak Cement Factory Road, Chhatak-3080',
    officeHours: 'Sunday - Thursday: 9:00 AM - 5:00 PM',
    servicesProvided: [
      'Industrial Zone & Lime Factory Environmental Checks',
      'Surma River Ferry & Sand Quarry Revenue Regulation',
      'Rural Infrastructure Development Under ADP',
    ],
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
    termOrBatch: '36th BCS (Administration)',
    emergencyHotline: '01730-331090',
    jurisdictionNotes: 'Chhatak Municipality and 13 Unions',
  },

  // 24. UNO Jagannathpur
  {
    id: 'snm-uno-jagannathpur',
    name: 'Sajedul Islam',
    nameBangla: 'সাজেদুল ইসলাম',
    designation: 'Upazila Nirbahi Officer (UNO), Jagannathpur',
    designationBangla: 'উপজেলা নির্বাহী অফিসার (ইউএনও), জগন্নাথপুর',
    department: 'Civil Administration',
    roleType: 'official',
    division: 'Sylhet',
    district: 'Sunamganj',
    upazila: 'Jagannathpur',
    union: 'Jagannathpur Pourashava',
    office: 'Upazila Parishad Complex, Jagannathpur, Sunamganj',
    officeBangla: 'উপজেলা পরিষদ কমপ্লেক্স, জগন্নাথপুর, সুনামগঞ্জ',
    phone: '+880 2996665100',
    altPhone: '+880 1730-331092',
    email: 'unojagannathpur@mopa.gov.bd',
    address: 'Bazar Road, Jagannathpur, Sunamganj-3060',
    officeHours: 'Sunday - Thursday: 9:00 AM - 5:00 PM',
    servicesProvided: [
      'British-Bangladeshi Expatriate Land & Asset Protection Cell',
      'Polder Embankment Repair Committee Lead',
      'Primary Education & Stipend Distribution Verification',
    ],
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&auto=format&fit=crop&q=80',
    termOrBatch: '37th BCS (Administration)',
    emergencyHotline: '01730-331092',
    jurisdictionNotes: 'Jagannathpur Pourashava and 8 Unions',
  },

  // ==================== HABIGANJ DISTRICT ====================
  // 25. Deputy Commissioner Habiganj
  {
    id: 'hbg-dc-1',
    name: 'Dr. Md. Faridur Rahman',
    nameBangla: 'ড. মো. ফরিদুর রহমান',
    designation: 'Deputy Commissioner & District Magistrate (DC), Habiganj',
    designationBangla: 'জেলা প্রশাসক ও জেলা ম্যাজিস্ট্রেট (ডিসি), হবিগঞ্জ',
    department: 'Civil Administration',
    roleType: 'official',
    division: 'Sylhet',
    district: 'Habiganj',
    upazila: 'Habiganj Sadar',
    union: 'Habiganj Pourashava',
    office: "Deputy Commissioner's Office, Habiganj Collectorate",
    officeBangla: 'জেলা প্রশাসকের কার্যালয়, হবিগঞ্জ কালেক্টরেট',
    phone: '+880 2996671001',
    altPhone: '+880 1713-000504',
    email: 'dchabiganj@mopa.gov.bd',
    address: 'Nimtola, Court Road, Habiganj-3300',
    officeHours: 'Sunday - Thursday: 9:00 AM - 5:00 PM',
    servicesProvided: [
      'Industrial Park & Special Economic Zone Facilitation',
      'Natural Gas Field Security Coordination',
      'Haor Protection & Agricultural Output Maximization',
      'Citizen Public Hearing (Every Wednesday)',
    ],
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=300&auto=format&fit=crop&q=80',
    termOrBatch: '24th BCS (Administration)',
    emergencyHotline: '02996671005',
    jurisdictionNotes: 'Habiganj District (9 Upazilas, 6 Municipalities)',
  },

  // 26. Superintendent of Police (SP) Habiganj
  {
    id: 'hbg-sp-1',
    name: 'Md. Rezaul Haque Khan',
    nameBangla: 'মো. রেজাউল হক খান',
    designation: 'Superintendent of Police (SP), Habiganj',
    designationBangla: 'পুলিশ সুপার (এসপি), হবিগঞ্জ',
    department: 'Law Enforcement & Police',
    roleType: 'official',
    division: 'Sylhet',
    district: 'Habiganj',
    upazila: 'Habiganj Sadar',
    union: 'Habiganj Pourashava',
    office: 'District Police Office, Shaheed Minar Road, Habiganj',
    officeBangla: 'জেলা পুলিশ সুপারের কার্যালয়, হবিগঞ্জ',
    phone: '+880 2996671200',
    altPhone: '+880 1713-374380',
    email: 'sphabiganj@police.gov.bd',
    address: 'Police Lines, Habiganj-3300',
    officeHours: '24/7 Law Enforcement',
    servicesProvided: [
      'Dhaka-Sylhet Highway Traffic & Safety Patrolling',
      'Border Smuggling & Narcotics Control',
      'Citizen Police Verification & Thana Management',
    ],
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    termOrBatch: '25th BCS (Police)',
    emergencyHotline: '999 / 01713-374380',
    jurisdictionNotes: 'Habiganj District & Highway Corridors',
  },

  // 27. UNO Nabiganj
  {
    id: 'hbg-uno-nabiganj',
    name: 'Anupam Das Anup',
    nameBangla: 'অনুপম দাস অনুপ',
    designation: 'Upazila Nirbahi Officer (UNO), Nabiganj',
    designationBangla: 'উপজেলা নির্বাহী অফিসার (ইউএনও), নবীগঞ্জ',
    department: 'Civil Administration',
    roleType: 'official',
    division: 'Sylhet',
    district: 'Habiganj',
    upazila: 'Nabiganj',
    union: 'Nabiganj Pourashava',
    office: 'Upazila Parishad Complex, Nabiganj, Habiganj',
    officeBangla: 'উপজেলা পরিষদ কমপ্লেক্স, নবীগঞ্জ, হবিগঞ্জ',
    phone: '+880 2996674100',
    altPhone: '+880 1730-331100',
    email: 'unonabiganj@mopa.gov.bd',
    address: 'Hospital Road, Nabiganj, Habiganj-3370',
    officeHours: 'Sunday - Thursday: 9:00 AM - 5:00 PM',
    servicesProvided: [
      'Expatriate Community Grievances & Asset Guarding',
      'Rural Electrification & Bridge Infrastructure Monitoring',
      'Union Parishad Budget Verification & Governance',
    ],
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
    termOrBatch: '36th BCS (Administration)',
    emergencyHotline: '01730-331100',
    jurisdictionNotes: 'Nabiganj Pourashava and 13 Unions',
  },

  // 28. UNO Madhabpur
  {
    id: 'hbg-uno-madhabpur',
    name: 'Manjur Ahsan',
    nameBangla: 'মঞ্জুর আহসান',
    designation: 'Upazila Nirbahi Officer (UNO), Madhabpur',
    designationBangla: 'উপজেলা নির্বাহী অফিসার (ইউএনও), মাধবপুর',
    department: 'Civil Administration',
    roleType: 'official',
    division: 'Sylhet',
    district: 'Habiganj',
    upazila: 'Madhabpur',
    union: 'Madhabpur Pourashava',
    office: 'Upazila Parishad Complex, Madhabpur, Habiganj',
    officeBangla: 'উপজেলা পরিষদ কমপ্লেক্স, মাধবপুর, হবিগঞ্জ',
    phone: '+880 2996676100',
    altPhone: '+880 1730-331102',
    email: 'unomadhabpur@mopa.gov.bd',
    address: 'Dhaka-Sylhet Highway Road, Madhabpur, Habiganj',
    officeHours: 'Sunday - Thursday: 9:00 AM - 5:00 PM',
    servicesProvided: [
      'Shahjibazar Power Station & Industrial Corridor Safety',
      'Border Market (Haat) Monitoring & Custom Coordination',
      'Agricultural Extension & Fertilizer Subsidy Enforcement',
    ],
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&auto=format&fit=crop&q=80',
    termOrBatch: '37th BCS (Administration)',
    emergencyHotline: '01730-331102',
    jurisdictionNotes: 'Madhabpur Pourashava and 11 Unions',
  },
];

export const SYLHET_EMERGENCY_HOTLINES = [
  {
    name: 'National Emergency Service',
    nameBangla: 'জাতীয় জরুরি সেবা',
    number: '999',
    description: 'Police, Fire Service, Ambulance',
    badge: 'Toll-Free 24/7',
    iconColor: 'bg-red-500',
  },
  {
    name: 'Government Services Helpline',
    nameBangla: 'সরকারি সেবা হেল্পলাইন',
    number: '333',
    description: 'Information & Citizen Grievance Redress',
    badge: '24/7 Toll-Free',
    iconColor: 'bg-emerald-600',
  },
  {
    name: 'SMP Police Control Room',
    nameBangla: 'সিলেট মেট্রোপলিটন পুলিশ',
    number: '01713-374300',
    description: 'Sylhet City 24/7 Police Dispatch',
    badge: 'Direct Line',
    iconColor: 'bg-blue-600',
  },
  {
    name: 'Sylhet Fire Service Control',
    nameBangla: 'সিলেট ফায়ার সার্ভিস',
    number: '01730-032222',
    description: 'Fire & Water Rescue Command',
    badge: 'Immediate',
    iconColor: 'bg-amber-600',
  },
  {
    name: 'MAG Osmani Hospital Emergency',
    nameBangla: 'ওসমানী মেডিকেল জরুরি বিভাগ',
    number: '02996636000',
    description: '24/7 Trauma & Ambulance Command',
    badge: 'Medical ER',
    iconColor: 'bg-rose-600',
  },
  {
    name: 'Land Service Hotline',
    nameBangla: 'ভূমি সেবা হেল্পলাইন',
    number: '16122',
    description: 'e-Mutation & Khatian Assistance',
    badge: 'Govt Helpline',
    iconColor: 'bg-teal-600',
  },
];

// Re-export backward compatibility
export const SAMPLE_RECORDS = SYLHET_DIRECTORY_DATA;
